export const typingTestConfig: any = {
  text: {
    Basic: [
      "Subhash Chandra Bose was a brave leader. He wanted India to be free. He made the Indian National Army. He told people to fight for freedom. He said, Give me blood, and I will give you freedom! He disappeared in a plane crash. People still remember him as a great hero.",
      "Mahatma Gandhi believed in peace. He fought against British rule without violence. He led the Salt March to show protest. He walked for many days with his followers. People joined him and made salt. The British got scared. His truth and kindness helped India become free. He is called the Father of the Nation.",
      "Bhagat Singh was a young freedom fighter. He wanted British rule to end. He and his friends threw a bomb in the British Assembly. He was caught and put in jail. He was very brave and never got scared. He smiled before he was hanged. People remember him as a fearless hero.",
      "Abdul Kalam loved science. He studied hard and became a great scientist. He helped India make rockets and missiles. People called him the Missile Man of India. Later, he became the President of India. He loved children and told them to dream big. He always believed that hard work brings success.",
      "Tenali Rama was very smart. One night, thieves planned to rob his house. He loudly told his wife to hide gold in the well. The thieves heard and dug the well all night. But there was no gold. He tricked them and saved his treasure. The thieves ran away, feeling foolish.",
      "Rani Lakshmibai was a brave queen. The British wanted to take her kingdom. She refused to give up. She fought like a warrior. She rode into battle with her sword. She had her little son on her back. She fought till her last breath. People still remember her courage and bravery.",
      "Aryabhata was a great mathematician. He discovered zero and helped in making modern numbers. Before him, people did not have a proper way to count. His work helped the world in math and astronomy. Because of him, numbers became easier to use. Today, the world remembers him as a genius.",
      "Swami Vivekananda went to America for a speech. He started by saying, Brothers and sisters of America. Everyone clapped for a long time. He told people that all religions are equal. He spoke about India's great culture. People respected him. He made the world know about India's wisdom and spirituality.",
      "Chandrayaan was India's big moon mission. Indian scientists worked hard to send a rocket to the Moon. It found water on the Moon. Later, Chandrayaan-3 landed safely. India became the first country to land on the Moon's south pole. The whole world praised India's success. It was a proud moment.",
      "A fisherman sits by the river. He throws his net. He waits. No fish come. He tries again. Suddenly, he catches a big fish. He is very happy. He takes the fish home. His family cooks it. They all enjoy a nice meal together.",
      "The Eiffel Tower grows in summer! Made of iron, it expands in heat, growing up to 6 inches taller. Over 7 million people visit annually, making it one of the world's most famous landmarks.",
      "Octopuses have three hearts. Two pump blood to the gills, and one to the body. When swimming, the body heart stops, which is why they prefer crawling.",
      "Bananas are berries, but strawberries aren't. Botanically, berries have seeds inside. Bananas qualify, while strawberries have seeds on the outside, making them 'false fruits'.",
      "Honey never spoils. Archaeologists found 3,000-year-old honey in Egyptian tombs, still edible. Its natural composition and low moisture prevent bacteria growth.",
      "Sharks existed before trees. Sharks have been around for over 400 million years, while trees appeared about 350 million years ago. They've survived five mass extinctions.",
      "Wombat poop is cube-shaped. This helps prevent it from rolling away, marking territory effectively. Their unique intestines shape the waste into cubes.",
      "The shortest war lasted 38 minutes. In 1896, Zanzibar surrendered to Britain after a brief conflict. It's the shortest recorded war in history.",
      "Polar bears are nearly invisible to infrared cameras. Their thick fur and fat insulate heat so well that they blend into their icy surroundings in thermal imaging.",
      "Venus has the longest day. One day on Venus lasts 243 Earth days, longer than its year (225 Earth days). It also rotates backward compared to most planets.",
      "Cows have best friends. Studies show cows form strong bonds and get stressed when separated from their preferred companions. They're social animals with complex emotions.",
    ],
    Intermediate: [
      "Many princes try to win Draupadi by shooting a spinning target. They all fail. Arjuna, dressed as a poor man, picks up the bow. He aims carefully and shoots the target. The arrow hits perfectly. Draupadi garlands him. The princes are shocked. Arjuna takes Draupadi home, where Kunti unknowingly asks them to share her.",
      "Bhishma, a great warrior, takes a vow never to marry. He does this so his father, King Shantanu, can marry a fisherwoman. Because of his vow, Bhishma never becomes king. Instead, he protects the kingdom. The gods bless him with the power to choose his own time of death.",
      "Duryodhana visits the Pandavas' palace, built by the architect Mayasura. The palace is full of magical illusions. He mistakes a glass floor for water and lifts his clothes. He falls into real water thinking it is glass. Draupadi laughs at him. Angry and humiliated, Duryodhana swears revenge, leading to the game of dice.",
      "Indra, Arjuna's father, asks Karna for his divine armor and earrings, which make him invincible. Karna, known for his generosity, gives them away despite knowing it will make him weaker. Pleased, Indra blesses him with a powerful spear. But Karna can use it only once, which later leads to his downfall.",
      "Before the war, Arjuna hesitates to fight his own family. Krishna, his charioteer, explains the truth of life and duty. He reveals his divine form-brighter than a thousand suns. Arjuna realizes Krishna is God. Krishna teaches him about Dharma, and Arjuna gains the courage to fight in the war.",
      "Ekalavya, a tribal boy, secretly learns archery by practicing in front of Dronacharya's statue. When Drona learns this, he asks for Ekalavya's right thumb as Guru Dakshina. Without hesitation, Ekalavya cuts it off and gives it to him. Though he loses his skill, his devotion remains legendary.",
      "After losing everything in the dice game, Draupadi is humiliated in the Kaurava court. Dushasana tries to disrobe her, but Krishna saves her by providing endless cloth. Draupadi swears to keep her hair untied until she washes it with Dushasana's blood. Later, Bhima fulfills this vow by killing him in the war.",
      "Abhimanyu, Arjuna's son, learns how to enter the Chakravyuha battle formation but doesn't know how to escape. During the war, he bravely fights alone against many warriors. He destroys most of the formation, but the Kauravas break the rules and kill him unfairly. His sacrifice inspires the Pandavas to fight harder.",
      "After the war, Gandhari, the Kauravas' mother, is heartbroken. She believes Krishna could have prevented the war. In grief, she curses him, saying his Yadava clan will also be destroyed. Krishna accepts the curse, knowing it is destiny. Years later, his people fight among themselves, and the Yadava dynasty ends.",
      "After ruling for years, the Pandavas renounce the throne and start a journey to the Himalayas. One by one, they fall, as only the pure-hearted can reach heaven. Yudhishthira, the eldest, alone reaches the gates of heaven, accompanied by a loyal dog, who turns out to be Dharma, testing his virtue.",
      "Before marriage, Kunti receives a boon to call any god and have a son. Out of curiosity, she calls Surya, the sun god. She gives birth to Karna but abandons him in the river. A charioteer finds and raises him. Later, Karna becomes one of the strongest warriors in the war.",
      "Shakuni, Duryodhana's uncle, tricks Yudhishthira into a game of dice. Yudhishthira keeps gambling and loses everything-his kingdom, brothers, and even Draupadi. When Draupadi is humiliated in court, she prays to Krishna, who saves her. This event sows the seeds of war between the Pandavas and Kauravas.",
      "As a child, Krishna tells the villagers to worship Govardhan Hill instead of Indra. Angry, Indra sends heavy rain. Krishna lifts the hill on his little finger, sheltering everyone. After seven days, Indra realizes his mistake and stops the rain. The people rejoice, and Krishna is worshipped as Govardhan Giridhari.",
      "Shikhandi was born as Amba in a past life and vowed revenge against Bhishma. Reborn as Shikhandi, she fights in the war. Bhishma refuses to fight someone born as a woman, making him vulnerable. Arjuna uses this chance to shoot Bhishma, leading to his downfall.",
      "Drona, the great teacher, is unstoppable in war. Krishna tricks him by spreading a false rumor that his son, Ashwatthama, is dead. When Drona hears this, he loses hope and stops fighting. Drupada's son, Dhrishtadyumna, seizes the moment and kills him, fulfilling his vow of revenge.",
      "Prince Rama is to be king, but Queen Kaikeyi wants her son Bharata to rule. She asks King Dasharatha to send Rama to the forest for 14 years. Rama obeys. His wife Sita and brother Lakshmana go with him. Dasharatha dies of sorrow. Bharata rules but waits for Rama's return.",
      "In the forest, demon king Ravana tricks Sita. He takes the form of a sage and asks for food. When Sita steps out, he kidnaps her and flies to Lanka. Jatayu, a great bird, tries to save her but fails. Sita waits for Rama to rescue her.",
      "Hanuman, Rama's devotee, flies to Lanka to find Sita. He meets her in Ashoka Vatika, where Ravana keeps her. Hanuman gives Rama's ring to Sita to give her hope. He warns Ravana to return Sita. When Ravana refuses, Hanuman burns part of Lanka and returns to Rama.",
      "Rama and his army reach the sea but cannot cross it. Rama prays to the sea god. With Hanuman and the monkey army, they build a stone bridge. The stones float by Lord Rama's name. The army crosses and prepares for war against Ravana.",
      "A great battle begins. Many warriors die. Ravana is strong, but Rama prays and shoots a special arrow at his heart. Ravana falls, defeated. Sita is freed. Rama, Sita, and Lakshmana return to Ayodhya. The people celebrate with lamps, which is now the festival of Diwali.",
    ],
    Advanced: [
      "Rama, the rightful heir to Ayodhya's throne, is exiled for fourteen years due to Queen Kaikeyi's cunning demand. Despite the injustice, he accepts his fate with dignity. Sita and Lakshmana accompany him to the forest, leaving behind a grieving King Dasharatha, who eventually succumbs to sorrow and passes away.",
      "In the forest, Ravana's demon Maricha disguises himself as a golden deer to enchant Sita. She pleads with Rama to capture it. As Rama chases the illusion, Maricha mimics his voice, calling for help. Lakshmana hesitantly leaves to assist, leaving Sita vulnerable to Ravana's wicked abduction.",
      "Endowed with immense strength, Hanuman leaps across the vast ocean to Lanka in search of Sita. Navigating through Ravana's heavily guarded kingdom, he locates her in Ashoka Vatika. He reassures her of Rama's impending rescue and, after wreaking havoc in Lanka, returns to inform Rama of her whereabouts.",
      "A fierce battle ensues between Rama's army and Ravana's formidable forces. The war sees powerful warriors slain on both sides. Ravana's tenacity makes him nearly invincible, but Rama, invoking divine energy, strikes him down with the Brahmastra. The demon king collapses, bringing an end to his tyranny.",
      "Despite rescuing Sita, Rama demands she prove her purity. She steps into a blazing fire, unscathed, as the flames refuse to harm her. This divine testimony convinces all of her chastity. The couple returns to Ayodhya, where Rama is crowned king, marking the beginning of a golden era.",
      "Upon learning of Rama's exile, Bharata refuses to accept the throne. He seeks Rama in the forest, urging him to return. When Rama declines, Bharata takes his sandals, places them on Ayodhya's throne, and rules as a caretaker, awaiting his brother's return with unwavering devotion.",
      "As Ravana abducts Sita, the noble vulture Jatayu intervenes, battling the demon king with great valor. Though aged, he fights fiercely but is ultimately overpowered. Ravana slashes his wings and leaves him dying. Before perishing, Jatayu informs Rama of Sita's abduction, playing a crucial role in her rescue.",
      "Ravana's righteous brother, Vibhishana, repeatedly advises him to return Sita and seek peace. Enraged, Ravana banishes him. Vibhishana defects to Rama's side, offering strategic counsel. His wisdom helps Rama defeat Ravana, and after the war, he is crowned the rightful king of Lanka for his loyalty and virtue.",
      "Kumbhakarna, Ravana's giant brother, awakens from his deep slumber to join the war. Though he knows Ravana is wrong, he fights out of loyalty. With colossal strength, he devastates Rama's army but is ultimately slain. His death symbolizes the tragic consequences of blind allegiance.",
      "During battle, Lakshmana is fatally wounded. A divine physician prescribes the Sanjeevani herb from a distant mountain. Hanuman rushes to retrieve it but, unable to identify the herb, lifts the entire mountain and brings it back. The herb revives Lakshmana, and the war continues with renewed vigor.",
      "Standing on the battlefield, Arjuna is paralyzed by moral conflict, unwilling to fight his own kin. He questions dharma and the consequences of war. Krishna, his divine charioteer, urges him to rise above attachments, embrace duty, and act selflessly, teaching him the essence of righteousness and eternal truth.",
      "Krishna enlightens Arjuna on the imperishable nature of the soul. He explains that the body perishes, but the atman (soul) is eternal, neither born nor destroyed. Just as a person discards old garments, the soul sheds the body and moves forward. Understanding this truth liberates one from the fear of death.",
      "Krishna advocates Karma Yoga, the path of selfless action. He instructs Arjuna to act without attachment to results. Performing one's duty with dedication, free from selfish desires, leads to liberation. True yoga is working with devotion, surrendering the fruits of labor to the divine, without seeking personal gain.",
      "To reveal his divine power, Krishna grants Arjuna the ability to perceive his Vishvarupa-a boundless, infinite form encompassing the entire universe. Arjuna witnesses countless gods, beings, and the cycle of creation and destruction within Krishna. Awestruck, he surrenders completely, realizing Krishna as the supreme reality beyond mortal comprehension.",
      "Krishna explains the three gunas-Sattva (purity, wisdom), Rajas (passion, desire), and Tamas (ignorance, inertia). These qualities bind the soul to worldly existence. True liberation comes from transcending them, attaining a state of pure consciousness, free from material influences, and realizing the eternal self beyond the cycle of birth and death.",
      "Krishna declares Bhakti Yoga as the supreme path. He assures Arjuna that unwavering devotion leads to divine grace. By surrendering wholeheartedly, free from ego and doubt, a devotee attains union with the divine. Krishna promises, Abandon all dharmas and surrender unto me; I shall liberate you from all sins.",
      "Theodore's mind overflowed with unfinished inventions, tangled in indecision. One evening, he sketched his ideas without judgment, realizing creation isn't about clarity from the start-it's about embracing chaos until patterns emerge.",
    ],
  },
  numbers: {
    Basic: [
      "123 456 789 012 345 901 234 567 890 123 678 901 234 567",
      "678 901 234 567 890 123 456 789 012 345 345 678 901 234 567",
      "234 567 890 123 456 901 234 567 890 123 678 901 234 567",
      "789 012 345 678 901 123 456 789 012 345 345 678 901 234 567",
      "345 678 901 234 567 901 234 567 890 123 678 901 234 567",
      "901 234 567 890 123 123 456 789 012 345 345 678 901 234 567",
    ],
    Intermediate: [
      "314 159 265 358 979 223 606 797 749 979 141 421 356 237",
      "271 828 182 845 904 173 205 080 756 887 314 159 265 358",
      "161 803 398 874 989 223 606 797 749 979 141 421 356 237",
      "141 421 356 237 309 173 205 080 756 887 314 159 265 358",
      "173 205 080 756 887 223 606 797 749 979 141 421 356 237",
      "223 606 797 749 979 173 205 080 756 887 314 159 265 358",
    ],
    Advanced: [
      "1.618033 9.81 299792458 6.62607015 2.99792458 2.718281 1.414213 137.035999 1.618033 9.81 299792458",
      "6.62607015 2.99792458 1.618033 9.81 299792458 2.718281 1.414213 137.035999 6.62607015 2.99792458",
      "2.718281 1.414213 137.035999 3.141592 0.577215 4.669201 6.62607015 2.99792458 2.718281 1.414213 137.035999",
      "3.141592 0.577215 4.669201 1.732050 57.29578 0.693147 2.718281 1.414213 137.035999 0.301030 23.14069 0.017453",
      "1.732050 57.29578 0.693147 3.141592 0.577215 4.669201 2.718281 1.414213 137.035999 0.301030 23.14069 0.017453",
      "0.301030 23.14069 0.017453 2.718281 1.414213 137.035999 3.141592 0.577215 4.669201 1.732050 57.29578 0.693147",
    ],
  },
  coding: {
    Basic: [
      "console.log('Hello World');",
      "const sum = (a, b) => a + b;",
      "let name = 'Alice'; console.log('Welcome, ' + name + '!');",
      "function greet() { return 'Good Morning!'; } console.log(greet());",
      "const numbers = [1, 2, 3]; numbers.forEach(num => console.log(num));",
      "let age = 25; if (age >= 18) { console.log('Adult'); } else { console.log('Minor'); }",
    ],
    Intermediate: [
      "for (let i = 0; i < 10; i++) { console.log(i); }",
      "if (condition) { executeFunction(); } else { handleError(); }",
      "const square = num => num * num; console.log(square(5));",
      "let user = { name: 'Bob', age: 30 }; console.log(`User: ${user.name}, Age: ${user.age}`);",
      "const arr = [10, 20, 30]; const doubled = arr.map(n => n * 2); console.log(doubled);",
      "function factorial(n) { let result = 1; for (let i = 2; i <= n; i++) { result *= i; } return result; } console.log(factorial(5));",
    ],
    Advanced: [
      "function fibonacci(n) { return n <= 1 ? n : fibonacci(n - 1) + fibonacci(n - 2); }",
      "const fetchData = async (url) => { const response = await fetch(url); return response.json(); };",
      "class Animal { constructor(name) { this.name = name; } speak() { console.log(`${this.name} makes a sound.`); } } class Dog extends Animal { speak() { console.log(`${this.name} barks.`); } } let dog = new Dog('Buddy'); dog.speak();",
      "const memoizedFactorial = (() => { const cache = {}; return function factorial(n) { if (n in cache) return cache[n]; cache[n] = n === 0 ? 1 : n * factorial(n - 1); return cache[n]; }; })(); console.log(memoizedFactorial(5));",
      "function debounce(func, delay) { let timeout; return (...args) => { clearTimeout(timeout); timeout = setTimeout(() => func(...args), delay); }; } const logMessage = debounce(() => console.log('Debounced!'), 300); window.addEventListener('resize', logMessage);",
      "const fetchAndProcessData = async (url) => { try { let response = await fetch(url); if (!response.ok) throw new Error('Network error'); let data = await response.json(); return process(data); } catch (error) { console.error(error); } };",
    ],
  },
  symbols: {
    Basic: [
      "@ # $ % ^ & * ( )",
      "! ? ~ ` + - _ =",
      "[ ] { } | \\ / : ; ' \"",
      "< > , .",
      "© ® ™ ✓ ✗",
      "° ∞ ≠ ≤ ≥ ± ∑",
    ],
    Intermediate: [
      "<div class='test'>Hello</div>",
      "function() => { return true; }",
      "[a-zA-Z0-9_]+@[a-zA-Z]+\\.[a-z]{2,}",
      "<meta charset='UTF-8' />",
      "const regex = /^\\d{3}-\\d{2}-\\d{4}$/;",
      "<script>alert('Injected!');</script>",
    ],
    Advanced: [
      "{ key: 'value', data: [1,2,3], callback: () => {} }",
      "while (*ptr != '\\0') { process(ptr++); }",
      "#define PI 3.14159",
      "SELECT * FROM users WHERE email LIKE '%@example.com'",
      "λx.x (Lambda Calculus Expression)",
      "$ echo 'Hello, World!' | grep 'World'",
    ],
  },
};
